# SPDX-FileCopyrightText: 2026 Methodic Games LLC
# SPDX-License-Identifier: 0BSD

paths:
  .github/workflows/release.yaml:
    ignore:
      # CHECK: Remove this exact diagnostic exception when actionlint supports
      # queue. https://github.com/rhysd/actionlint/issues/657
      - '^unexpected key "queue" for "concurrency" section[.] expected one of "cancel-in-progress", "group"$'
